flasher: allow to pre-select solution by env or aosc-arm.conf
Signed-off-by: Icenowy Zheng <icenowy@aosc.xyz>

diff --git a/aosc-arm-flasher b/aosc-arm-flasher
--- a/aosc-arm-flasher
+++ b/aosc-arm-flasher
@@ -12,43 +12,53 @@ if [ ! "$DEVICE" ]; then
 	exit 1
 fi
 
-available_sols=""
+if [ ! "$FLASHER_SOLUTION" ]; then
+	available_sols=""
 
-if [ ! -d ${TEST_ROOT}/usr/lib/aosc-os-arm-boot-flasher/solutions ]; then
-	echo "Cannot find any solutions installed." >&2
-	exit 1
-fi
-
-for i in ${TEST_ROOT}/usr/lib/aosc-os-arm-boot-flasher/solutions/*
-do
-	source "$i"
-	current_sol=$(basename "$i")
-	if "${current_sol}_is_available"; then
-		available_sols+=" ${current_sol}"
+	if [ ! -d ${TEST_ROOT}/usr/lib/aosc-os-arm-boot-flasher/solutions ]; then
+		echo "Cannot find any solutions installed." >&2
+		exit 1
 	fi
-done
 
-if [ "${available_sols}" = "" ]; then
-	echo "No available solution found." >&2
-	exit 1
-fi
+	for i in ${TEST_ROOT}/usr/lib/aosc-os-arm-boot-flasher/solutions/*
+	do
+		source "$i"
+		current_sol=$(basename "$i")
+		if "${current_sol}_is_available"; then
+			available_sols+=" ${current_sol}"
+		fi
+	done
 
-echo "Available solutions: ${available_sols}"
-echo "Please choose one solution: "
-read used_sol
-
-found=0
-for i in $available_sols
-do
-	if [ "$i" = "$used_sol" ]; then
-		found=1
-		break
+	if [ "${available_sols}" = "" ]; then
+		echo "No available solution found." >&2
+		exit 1
 	fi
-done
 
-if ((\!$found)); then
-	echo "Invalid solution." >&2
-	exit 1
+	echo "Available solutions: ${available_sols}"
+	echo "Please choose one solution: "
+	read used_sol
+
+	found=0
+	for i in $available_sols
+	do
+		if [ "$i" = "$used_sol" ]; then
+			found=1
+			break
+		fi
+	done
+
+	if ((\!$found)); then
+		echo "Invalid solution." >&2
+		exit 1
+	fi
+else
+	if [ -e "${TEST_ROOT}/usr/lib/aosc-os-arm-boot-flasher/solutions/${FLASHER_SOLUTION}" ]; then
+		source "${TEST_ROOT}/usr/lib/aosc-os-arm-boot-flasher/solutions/${FLASHER_SOLUTION}"
+		used_sol="${FLASHER_SOLUTION}"
+	else
+		echo "Invalid solution specified in aosc-arm.conf or environment variables." >&2
+		exit 1
+	fi
 fi
 
 _sol_flash_cap_varname="${used_sol}_flash_cap"
